# Generated by Django 3.2.9 on 2021-11-20 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211119_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.images'),
        ),
    ]
